dj_femme/src/femme/femme/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('femme-admin/', admin.site.urls),
    path('', include("web.urls", namespace="web")),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dj_femme/src/femme/web/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('redirect-test/', views.test, name="test_redirect"),
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('registration/', views.registration, name="registration"),
]

app_name = "web"

dj_femme/src/femme/web/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


# Create your models here.
class RegistrationClass(models.Model):
    name = models.CharField(max_length=128)
    email = models.EmailField()
    phone = models.CharField(max_length=128)
    education = models.CharField(max_length=128)
    dob = models.DateField()
    message = models.TextField()

    class Meta:
        db_table = 'web_registration'
        verbose_name = _('registration')
        verbose_name_plural = _('registrations')

    def __unicode__(self):
        return self.name


class AboutClass(models.Model):
    title = models.CharField(max_length=128)
    content = models.TextField()
    image = models.ImageField(upload_to="web/about/")

    class Meta:
        db_table = 'web_about'
        verbose_name = _('about')
        verbose_name_plural = _('abouts')

    def __unicode__(self):
        return self.title

dj_femme/src/femme/web/forms.py
from django import forms
from django.forms import DateInput
from django.forms import EmailInput
from django.forms.widgets import TextInput
from django.utils.translation import gettext_lazy as _
from web.models import RegistrationClass


class RegistrationForm(forms.ModelForm):
    class Meta:
        model = RegistrationClass
        # fields = ['name', 'email']
        # exclude = ['email', 'phone']
        fields = '__all__'

        widgets = {
            'name': TextInput(attrs={'class': 'required', 'placeholder': 'Name'}),
            'email': EmailInput(attrs={'class': 'required', 'placeholder': 'Email'}),
            'phone': TextInput(attrs={'class': 'required', 'placeholder': 'Phone'}),
            'education': TextInput(attrs={'class': 'required', 'placeholder': 'Education'}),
            'dob': DateInput(attrs={'class': 'required', 'placeholder': 'Date of Birth'}),
            'message': TextInput(attrs={'class': 'required', 'placeholder': 'Message'}),
        }

        error_messages = {
            'name': {
                'required': _("Name field is required!"),
            },
            'email': {
                'required': _("E-mail field is required!"),
            },
            'phone': {
                'required': _("Phone field is required!"),
            },
            'education': {
                'required': _("Education field is required!"),
            },
            'dob': {
                'required': _("Date of birth is required!"),
            },
        }

        labels = {
            'email': "E-mail",
            'message': "What is in your mind?",
        }

dj_femme/src/femme/web/views.py
# from django.http.response import HttpResponse, HttpResponseRedirect
# from django.urls import reverse


# Create your views here.
# def index(request):
#     return HttpResponseRedirect(reverse('web:test_redirect'));
#
# # RESPONSE REDIRECT
# def test(request):
#     return HttpResponse("Hello Django Again from test redirect");

from django.shortcuts import render
from web.models import AboutClass, RegistrationClass
from django.http.response import HttpResponse
from web.forms import RegistrationForm
from web.functions import generate_form_errors
import json
from django.urls import reverse


def index(request):
    # all()  -- return -- queryset
    # filter() -- return -- queryset
    # exclude() -- return -- queryset
    # get() -- return -- object

    _about_instances = AboutClass.objects.all()
    _form = RegistrationForm
    context = {
        "app_title": "Home",
        "about_instances": _about_instances,
        "form": _form,
        "is_home": True,
    }
    return render(request, 'web/index.html', context);


def about(request):
    _about_instances = AboutClass.objects.all()
    context = {
        "app_title": "About",
        "about_instances": _about_instances,
        "is_about": True,
    }
    return render(request, 'web/about.html', context);


def registration(request):
    if request.method == "POST":
        '''    HTML FORM SUBMISSION
        _name = request.POST.get('name')
        _email = request.POST.get('email')
        _phone = request.POST.get('phone')
        _education = request.POST.get('education')
        _dob = request.POST.get('dob')
        _message = request.POST.get('message')
        RegistrationClass.objects.create(
            name=_name, email=_email, phone=_phone, education=_education, dob=_dob, message=_message
        )
        '''
        '''   DJANGO FORM SUBMISSION   '''
        _form = RegistrationForm(request.POST)
        if _form.is_valid():
            _form.save()
            response_data = {
                'status': "true",
                'title': "Successfully submitted",
                'message': "message successfully submitted",
            }
        else:
            message = generate_form_errors(_form, formset=False)
            response_data = {
                'status': "false",
                'stable': "true",
                'title': "Form validation error",
                'message': message,
            }
        return HttpResponse(json.dumps(response_data), content_type='application/javascript')
    else:
        return HttpResponse("invalid request!")

dj_femme/src/femme/templates/web/about.html
{% extends 'web/base.html' %}
{% load static %}
{% block content %}

    <section id="about">
        <section class="wrapper">
            {% if about_instances %}
                <ul>
                    {% for about in about_instances %}
                        <li>
                            <div class="top">
                                <div class="img">
                                    <img src="{{ about.image.url }}" alt="" title="">
                                </div>
                            </div>
                            <div class="bottom">
                                <h3>{{ about.title }}</h3>
                                <p>{{ about.content }}</p>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
                <br class="clear">
            {% else %}
                <p>No data found!</p>
            {% endif %}
        </section>
    </section>
{% endblock %}

dj_femme/src/femme/templates/web/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
        {% load static %}
		<meta charset="utf-8" />
		<title>{{ app_title }} | {{ app_caption }}</title>
		<link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}" />
		<link rel="stylesheet" href="{%  static 'css/style.css' %}" type="text/css" />
        <link rel="stylesheet" href="{%  static 'css/ajax-django.css' %}" type="text/css" />
        <link rel="stylesheet" href="{%  static 'css/sweet-alert.css' %}" type="text/css" />
		<meta name="viewport" content="width=device-width; initial-scale=1.0" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/ajax-django.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/sweet-alert.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
	</head>
	<body>
		<section id="top">
			<section class="wrapper">
				<header>
					<h1><a href="index.html" title="Femme"><img src="{% static 'images/header-logo.png' %}" alt="image" title="Femme"/></a></h1>
					<div id="myNav" class="sidenav" onclick="closeNav()">
						<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
						<div class="overlay-content">
					    	<ul>
								<li><a onclick="closeNav()" href="{% url 'web:index' %}" title="Home">Home</a></li>
								<li><a onclick="closeNav()" href="{% url 'web:about' %}" title="About">About</a></li>
								<li><a onclick="closeNav()" href="{% url 'web:index' %}#features" title="Features">Features</a></li>
								<li class="last"><a onclick="closeNav()" href="{% url 'web:index' %}#contact" title="">Contact</a></li>
							</ul>
						</div>
					</div>
					<span class="openmenu" onclick="openNav()">&nbsp;</span>
					<br class="clear" />
				</header>
                {% if is_home %}
                    {% include 'web/includes/index-spotlight.html' %}
                {% elif is_about %}
                    {% include 'web/includes/about-spotlight.html' %}
                {% endif %}

			</section><!--(#top > .wrapper)-->
		</section><!--(#top)-->

        {% block content %}

        {% endblock %}

        <section id="contact">
			<section class="wrapper">
				<div class="head">
					<h3>Get in Touch</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam asperiores tenetur aliquid sit repellat, dolores eius quasi possimus ipsum explicabo cumque. Explicabo exercitationem dignissimos asperiores unde et est, expedita numquam?</p>
				</div>
				<ul>
					<li>
						<span><b class="icon icon1">&nbsp;</b></span>
						<p>2nd Floor,<br>Ashtamudi Tower,<br>SEZ IT Building Technopark <br>Kollam - 691501</p>
					</li>
					<li>
						<span><b class="icon icon2">&nbsp;</b></span>
						<p><a title="Email" href="mailto:hello@femme.com"> hello@femme.com</a></p>
					</li>
					<li>
						<span><b class="icon icon3">&nbsp;</b></span>
						<p><a title="Phone" href="tel:"> +91 9845213212</a></p>
						<p><a title="Phone" href="tel:">+91 9684578632</a></p>
					</li>
				</ul>
				<br class="clear">
				<span class="line one">&nbsp;</span>
				<section class="bottom">
					<a href="#" title="Twitter" target="_blank" class="icon Twitter"><img src="{% static 'images/tw.png' %}" alt="Image" title="Twitter" /></a>
					<a href="#" title="Facebook" target="_blank" class="fb"><img src="{% static 'images/fb.png' %}" alt="Image" title="Facebook" /></a>
					<a href="#" title="Google Plus" target="_blank" class="icon gplus"><img src="{% static 'images/gp.png' %}" alt="Image" title="Google Plus" /></a>
				</section>
			</section>
		</section>

		<footer>
			<section class="wrapper">
				<p>Powered By Femme. <span>&copy;</span> {% now 'Y' %} Femme. All rights reserved.</p>
			</section><!--(#footer > .bottom)-->
		</footer>

		<script>
			function openNav() {
			    document.getElementById("myNav").style.height = "100%";
			}

			function closeNav() {
			    document.getElementById("myNav").style.height = "0%";
			}
		</script>
	</body>
</html>

dj_femme/src/femme/templates/web/includes/about-spotlight.html
<section id="spotlight">
    <h2>{{ app_title }}</h2>
</section><!--(#top > .wrapper > #spotlight)-->

dj_femme/src/femme/templates/web/includes/index-spotlight.html
<section id="spotlight">
    <h2>The Secret of getting <br>Ahead is getting started</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab nobis culpa magni, quod vel a maxime deleniti error officia odit, dicta laudantium cumque nostrum maiores beatae laboriosam eius, aut alias?</p>
    <a title="Explore" href="#" class="button">Explore</a>
</section><!--(#top > .wrapper > #spotlight)-->