todoapp/src/todoapp/baseapp/urls.py
from django.urls import path
from . import views

app_name = "baseapp"

urlpatterns = [
    path('', views.index, name="home"),
    path('delete/<int:pk>/', views.delete, name="task_delete"),
    path('status/change/<int:pk>/', views.changestatus, name="change_status"),
    path('edit/<int:pk>/', views.edittask, name="edit_task"),
]

todoapp/src/todoapp/todoapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('baseapp.urls', namespace="baseapp")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todoapp/src/todoapp/baseapp/models.py
from django.db import models


class Task(models.Model):
    name = models.CharField(max_length=128)
    priority = models.IntegerField()
    status = models.IntegerField()
    created = models.DateField()
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    published = models.DateField()
    price = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return self.title

todoapp/src/todoapp/baseapp/forms.py
from django import forms
from django.forms import DateInput
from django.forms import Select
from django.forms import TextInput
from .models import Task, Book
from django.utils.translation import gettext_lazy as _

Choice_Priority = [
    ('', 'Open this select priority'),
    ('1', 'High priority'),
    ('2', 'Middle priority'),
    ('3', 'Low priority'),
]

Choice_Status = [
    ('', 'Open this select status'),
    ('1', 'Completed'),
    ('2', 'Working'),
    ('3', 'Pending'),
]


class TodoTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        exclude = ['is_deleted', ]
        fields = ['name', 'priority', 'status', 'created']
        widgets = {
            'name': TextInput(attrs={'class': 'required form-control',
                                     'placeholder': 'task task task'}),
            'priority': Select(attrs={'class': 'required form-select  ',
                                      'placeholder': 'Select priority'},
                               choices=Choice_Priority),
            'status': Select(attrs={'class': 'required form-select  ',
                                    'placeholder': 'Select status'},
                             choices=Choice_Status),
            'created': DateInput(attrs={'class': 'required form-control  ',
                                        'placeholder': 'Date',
                                        'type': 'date', 'data-format': 'yyyy-MM-dd'}),
        }
        error_messages = {
            'name': {
                'required': _("Task field is required."),
            },
            'priority': {
                'required': _("Priority field is required."),
            },
            'status': {
                'required': _("Status field is required."),
            },
            'created': {
                'required': _("Date field is required."),
            },
        }
        labels = {
            "name": "Task",
            "priority": "Select priority",
            "status": "Select status",
            "created": "Date",
        }


# class BookForm(forms.ModelForm):
#     class Meta:
#         model = Book
#         exclude = ['is_deleted', ]
#         fields = ['title', 'author', 'published', 'price']
#         widgets ={
#             'title': TextInput(attrs={'class': 'required form-control',
#                                       'placeholder': 'title title title'}),
#             'author': TextInput(attrs={'class': 'required form-control',
#                                       'placeholder': 'task task task'}),
#             'published': DateInput(attrs={'class': 'required form-control  ',
#                                       'placeholder': 'Date',
#                                       'type': 'date', 'data-format': 'yyyy-MM-dd'}),
#             'price': TextInput(attrs={'class': 'required form-control',
#                                       'placeholder': 'task task task'}),
#             choices = Choice_Status),
#         }
#         error_messages = {
#             'title': {
#                 'required': _("title field is required."),
#             },
#             'price': {
#                 'required': _("price field is required."),
#             }
#         }

todoapp/src/todoapp/baseapp/views.py
from django.shortcuts import render, redirect
from .models import Task, Book
from .forms import TodoTaskForm


def index(request):
    form = TodoTaskForm()
    data = Task.objects.all()
    if request.method == 'POST':
        form = TodoTaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('baseapp:home')
        else:
            print("Something went wrong!")

        context = {
            'project': "ToDo App",
            'title': "Home",
            'tasks': data,
        }
        return render(request, "baseapp/index.html", context=context)
    else:
        context = {
            'project': "ToDo App",
            'title': "Home",
            'tasks': data,
            'form': form,
        }
        return render(request, "baseapp/index.html", context=context)


# def book_view(request):
#     books = Book.objects.all()  # Fetch all books
#     book_form = BookForm()
#
#     if request.method == 'POST':
#         book_form = BookForm(request.POST)
#         if book_form.is_valid():
#             book_form.save()
#             return redirect('baseapp:book_view')  # Redirect back after saving
#
#     context = {
#         'project': "Book Management",
#         'title': "Books",
#         'books': books,
#         'book_form': book_form,
#     }
#     return render(request, "baseapp/books.html", context)


def book_view(request):
    book_form = Book.objects.all()
    context = {
        'project': "Book Management",
        'title': "Books",
        'book_form': book_form,
    }

    if request.method == "POST":
        title = request.POST.get("title")
        author = request.POST.get("author")
        published = request.POST.get("published")
        price = request.POST.get("price")

        if title and author and published and price:  # Ensure required fields are provided
            Book.objects.create(title=title, author=author, published=published, price=price)

    return render(request, "index.html", context)


def delete(request, pk):
    task = Task.objects.get(pk=pk)
    if request.method == 'POST':
        # SET is_deleted True; better than delete entire row from db
        # task.is_deleted = True
        # task.save()

        task.delete()
        return redirect('baseapp:home')
    else:
        context = {
            'project': "ToDo App",
            'title': "Delete",
        }
        return render(request, "baseapp/delete.html", context=context)


def changestatus(request, pk):
    # status set to 1 for completed task and save
    data = Task.objects.get(pk=pk)
    data.status = 1
    data.save()
    return redirect('baseapp:home')


def edittask(request, pk):
    instance = Task.objects.get(pk=pk)
    if request.method == 'POST':
        form = TodoTaskForm(request.POST or None, instance=instance)
        if form.is_valid():
            form.save()
            return redirect('baseapp:home')
        else:
            print("Something went wrong")
    else:
        form = TodoTaskForm(request.POST or None, instance=instance)
        context = {
            'project': "ToDo App",
            'title': "Update Task",
            'form': form,
        }
        return render(request, "baseapp/edit_task_detail.html", context=context)

todoapp/src/todoapp/templates/base/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{project}} | {{title}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'custom.css' %}" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
</head>
<body>
    <div class="container-fluid">
    {% block content %}
    {% endblock %}
    </div>

    {% block static %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    {% endblock %}
</body>
</html>

todoapp/src/todoapp/templates/baseapp/delete.html
{% extends 'base/base.html' %}
{% block content %}
<form method="post" action="{{url}}">
    {% csrf_token %}
    <p>Are you sure want to delete this task?</p> <br />
    <button class="btn btn-danger" type="submit">Force to Delete</button>
</form>
{% endblock %}

todoapp/src/todoapp/templates/baseapp/edit_task_detail.html
{% extends 'base/base.html' %}
{% block content %}
<div class="text-center">
    <div class="row pb-5">
        <h1 class="mx-auto">{{project}}</h1>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="card shadow p-3">
                    <form method="post" action="{{url}}">
                        {% csrf_token %}
                        {{form.as_p}}
                        <div class="position-relative container col-3 pt-3">
                            <button type="submit" class=" mx-auto btn btn-success">Update Task</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

todoapp/src/todoapp/templates/baseapp/index.html
{% extends 'base/base.html' %}
{% block content %}
<div class="text-center top-space">
    <div class="row pb-5">
        <h1 class="mx-auto">{{project}}</h1>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="card shadow p-3">
                    <form method="post" action="{{url}}">
                        {% csrf_token %}
                        <div class="form-floating mb-3">
                            {{form.name}}
                            <label for="{{form.name.id_for_label}}">{{form.name.label}}</label>
                        </div>
                        <div class="form-floating mb-3">
                            {{form.priority}}
                            <label for="{{form.priority.id_for_label}}">{{form.priority.label}}</label>
                        </div>
                        <div class="form-floating mb-3">
                            {{form.status}}
                            <label for="{{form.status.id_for_label}}">{{form.status.label}}</label>
                        </div>
                        <div class="form-floating mb-3">
                            {{form.created}}
                            <label for="{{form.created.id_for_label}}">{{form.created.label}}</label>
                        </div>
                        <div class="position-relative container col-3 pt-3">
                            <button type="submit" class=" mx-auto btn btn-success">Add Task</button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="col-md-6">
                <div class="card shadow p-3" style="height: 384px; overflow-y: scroll">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th scope="col">Task</th>
                            <th scope="col">Priority</th>
                            <th scope="col">Status</th>
                            <th scope="col">Handler</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for task in tasks %}
                        <tr>
                            <th scope="row">{{task.name}}</th>
                            {% if task.priority == 1 %}
                            <td class="align-middle">
                                <span class="badge bg-danger">High priority</span>
                            </td>
                            {% elif task.priority == 2 %}
                            <td class="align-middle">
                                <span class="badge bg-warning">Middle priority</span>
                            </td>
                            {% elif task.priority == 3 %}
                            <td class="align-middle">
                                <span class="badge bg-success">Low priority</span>
                            </td>
                            {% endif %}
                            {% if task.status == 1 %}
                            <td class="align-middle">
                                <span class="badge bg-success">Completed</span>
                            </td>
                            {% elif task.status == 2 %}
                            <td class="align-middle">
                                <span class="badge bg-info">Working</span>
                            </td>
                            {% elif task.status == 3 %}
                            <td class="align-middle">
                                <span class="badge bg-danger">Pending</span>
                            </td>
                            {% endif %}
                            <td class="align-middle">
                                <a href="{% url 'baseapp:edit_task' pk=task.pk %}"
                                   data-mdb-toggle="tooltip" title="Edit">
                                    <i class="fas fa-pen text-warning me-3"></i></a>
                                <a href="{% url 'baseapp:change_status' pk=task.pk %}"
                                   data-mdb-toggle="tooltip" title="Done">
                                    <i class="fas fa-check text-success me-3"></i></a>
                                <a href="{% url 'baseapp:task_delete' pk=task.pk %}"
                                   data-mdb-toggle="tooltip" title="Remove">
                                    <i class="fas fa-trash-alt text-danger"></i></a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <form method="post" action="{{ url }}">
    {% csrf_token %}
    <div class="form-floating mb-3">
        <input type="text" name="title" class="form-control" id="title">
        <label for="title">Book Title</label>
    </div>
    <div class="form-floating mb-3">
        <input type="text" name="author" class="form-control" id="author">
        <label for="author">Author</label>
    </div>
    <div class="form-floating mb-3">
        <input type="date" name="published" class="form-control" id="published">
        <label for="published">Published Date</label>
    </div>
    <div class="form-floating mb-3">
        <input type="number" name="price" class="form-control" id="price">
        <label for="price">Price</label>
    </div>
    <div class="position-relative container col-3 pt-3">
        <button type="submit" class="mx-auto btn btn-success">Add Book</button>
    </div>
    </form>

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="card shadow p-3">
                    <form method="post" action="{{url}}">
                        {% csrf_token %}
                        <div class="form-floating mb-3">
                            {{book.title}}
                            <label for="{{book.title.id_for_label}}">{{book.title.label}}</label>
                        </div>
                        <div class="form-floating mb-3">
                            {{book.author}}
                            <label for="{{book.author.id_for_label}}">{{book.author.label}}</label>
                        </div>
                        <div class="form-floating mb-3">
                            {{book.published}}
                            <label for="{{book.published.id_for_label}}">{{book.published.label}}</label>
                        </div>
                        <div class="form-floating mb-3">
                            {{book.price}}
                            <label for="{{book.price.id_for_label}}">{{book.price.label}}</label>
                        </div>
                        <div class="position-relative container col-3 pt-3">

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card shadow p-3">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">Task</th>
                    <th scope="col">Priority</th>
                    <th scope="col">Status</th>
                    <th scope="col">Handler</th>
                </tr>
                </thead>
                <tbody>


                </tbody>
            </table>
        </div>
    </div>
</div>



{% endblock %}

todoapp/src/todoapp/templates/baseapp/index_before_form.html
{% extends 'base/base.html' %}
{% block content %}
<div class="text-center">
    <div class="row pb-5">
        <h1 class="mx-auto">{{project}}</h1>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="card shadow p-3">
                    <form method="post" action="{{url}}">
                        {% csrf_token %}
                        <div class="form-floating mb-3">
                            <input type="text" class="form-control" name="task_title"
                                   id="floatingInput" placeholder="task task task">
                            <label for="floatingInput">Task</label>
                        </div>
                        <div class="form-floating">
                            <select class="form-select" id="floatingSelect" name="num_priority"
                                    aria-label="Floating label select example">
                                <option selected>Open this select priority</option>
                                <option value="1">High priority</option>
                                <option value="2">Middle priority</option>
                                <option value="3">Low priority</option>
                            </select>
                            <label for="floatingSelect">Select priority</label>
                        </div>
                        <div class="form-floating">
                            <select class="form-select" id="floatingSelect1" name="num_status"
                                    aria-label="Floating label select example">
                                <option selected>Open this select status</option>
                                <option value="1">Completed</option>
                                <option value="2">Working</option>
                                <option value="3">Pending</option>
                            </select>
                            <label for="floatingSelect1">Select status</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="date" class="form-control" name="task_date"
                                   id="floatingInput1" placeholder="task creation date">
                            <label for="floatingInput1">Date</label>
                        </div>
                        <div class="position-relative container col-3 pt-3">
                            <button type="submit" class=" mx-auto btn btn-success">Add Task</button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="col-md-6">
                <div class="card shadow p-3" style="height: 278px; overflow-y: scroll">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th scope="col">Task</th>
                            <th scope="col">Priority</th>
                            <th scope="col">Status</th>
                            <th scope="col">Handler</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for task in tasks %}
                        <tr>
                            <th scope="row">{{task.name}}</th>
                            {% if task.priority == 1 %}
                            <td class="align-middle">
                                <span class="badge bg-danger">High priority</span>
                            </td>
                            {% elif task.priority == 2 %}
                            <td class="align-middle">
                                <span class="badge bg-warning">Middle priority</span>
                            </td>
                            {% elif task.priority == 3 %}
                            <td class="align-middle">
                                <span class="badge bg-success">Low priority</span>
                            </td>
                            {% endif %}
                            {% if task.status == 1 %}
                            <td class="align-middle">
                                <span class="badge bg-success">Completed</span>
                            </td>
                            {% elif task.status == 2 %}
                            <td class="align-middle">
                                <span class="badge bg-info">Working</span>
                            </td>
                            {% elif task.status == 3 %}
                            <td class="align-middle">
                                <span class="badge bg-danger">Pending</span>
                            </td>
                            {% endif %}
                            <td class="align-middle">
                                <a href="{% url 'baseapp:edit_task' pk=task.pk %}"
                                   data-mdb-toggle="tooltip" title="Edit">
                                    <i class="fas fa-pen text-warning me-3"></i></a>
                                <a href="{% url 'baseapp:change_status' pk=task.pk %}"
                                   data-mdb-toggle="tooltip" title="Done">
                                    <i class="fas fa-check text-success me-3"></i></a>
                                <a href="{% url 'baseapp:task_delete' pk=task.pk %}"
                                   data-mdb-toggle="tooltip" title="Remove">
                                    <i class="fas fa-trash-alt text-danger"></i></a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}